<?php

/**
 * @file
 * Contains la_pills_analytics.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\la_pills\Entity\SessionEntityInterface;
use Drupal\la_pills_timer\Entity\LaPillsTimerEntityInterface;
use Drupal\la_pills_quick_feedback\Entity\LaPillsQuestionEntityInterface;
use Drupal\la_pills_quick_feedback\Entity\LaPillsQuestionnaireEntityInterface;
use Drupal\la_pills_onboarding\Entity\LaPillsUserPackageEntityInterface;
use Drupal\la_pills\FetchClass\SessionTemplate;
use Drupal\Core\Entity\EntityInterface;
use Drupal\user\UserInterface;

/**
 * Implements hook_help().
 */
function la_pills_analytics_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the la_pills_analytics module.
    case 'help.page.la_pills_analytics':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('LAPills statistics and analytics.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function la_pills_analytics_session_entity_insert(SessionEntityInterface $entity) {
  \Drupal::service('la_pills_analytics.manager')
    ->storeEntityAction($entity, 'create', \Drupal::request());
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function la_pills_analytics_session_entity_update(SessionEntityInterface $entity) {
  \Drupal::service('la_pills_analytics.manager')
    ->storeEntityAction($entity, 'update', \Drupal::request());
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function la_pills_analytics_session_entity_delete(SessionEntityInterface $entity) {
  \Drupal::service('la_pills_analytics.manager')
    ->storeEntityAction($entity, 'delete', \Drupal::request());
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function la_pills_analytics_la_pills_timer_entity_insert(LaPillsTimerEntityInterface $entity) {
  \Drupal::service('la_pills_analytics.manager')
    ->storeEntityAction($entity, 'create', \Drupal::request());
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function la_pills_analytics_la_pills_timer_entity_update(LaPillsTimerEntityInterface $entity) {
  \Drupal::service('la_pills_analytics.manager')
    ->storeEntityAction($entity, 'update', \Drupal::request());
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function la_pills_analytics_la_pills_timer_entity_delete(LaPillsTimerEntityInterface $entity) {
  \Drupal::service('la_pills_analytics.manager')
    ->storeEntityAction($entity, 'delete', \Drupal::request());
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function la_pills_analytics_la_pills_question_entity_insert(LaPillsQuestionEntityInterface $entity) {
  \Drupal::service('la_pills_analytics.manager')
    ->storeEntityAction($entity, 'create', \Drupal::request());
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function la_pills_analytics_la_pills_question_entity_update(LaPillsQuestionEntityInterface $entity) {
  \Drupal::service('la_pills_analytics.manager')
    ->storeEntityAction($entity, 'update', \Drupal::request());
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function la_pills_analytics_la_pills_question_entity_delete(LaPillsQuestionEntityInterface $entity) {
  \Drupal::service('la_pills_analytics.manager')
    ->storeEntityAction($entity, 'delete', \Drupal::request());
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function la_pills_analytics_la_pills_user_package_insert(LaPillsUserPackageEntityInterface $entity) {
  \Drupal::service('la_pills_analytics.manager')
    ->storeEntityAction($entity, 'create', \Drupal::request());
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function la_pills_analytics_la_pills_user_package_update(LaPillsUserPackageEntityInterface $entity) {
  \Drupal::service('la_pills_analytics.manager')
    ->storeEntityAction($entity, 'update', \Drupal::request());
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function la_pills_analytics_la_pills_user_package_delete(LaPillsUserPackageEntityInterface $entity) {
  \Drupal::service('la_pills_analytics.manager')
    ->storeEntityAction($entity, 'delete', \Drupal::request());
}

// TODO It would be better to have questionnaire as an object not an array
/**
 * Implements hook_questionnaire_answered().
 */
function la_pills_analytics_questionnaire_answered(array $questionnaire, SessionEntityInterface $entity) {
  $manager = \Drupal::service('la_pills_analytics.manager');
  $request = \Drupal::request();

  $manager->storeAction('answered', $request, [
    'entity' => $manager->getEntityData($entity),
    'questionnaire' => [
      'type' => 'embedded',
      'uuid' => $questionnaire['uuid'],
      'title' => $questionnaire['title'],
    ],
  ]);
}

/**
 * Implements hook_quick_feedback_answered().
 */
function la_pills_analytics_quick_feedback_answered(LaPillsQuestionnaireEntityInterface $questionnaire, SessionEntityInterface $entity) {
  $manager = \Drupal::service('la_pills_analytics.manager');
  $request = \Drupal::request();

  $manager->storeAction('answered', $request, [
    'entity' => $manager->getEntityData($entity),
    'questionnaire' => [
      'type' => 'quick_feedback',
      'id' => $questionnaire->id(),
      'uuid' => $questionnaire->uuid(),
      'title' => $questionnaire->label(),
    ],
  ]);
}

/**
 * Implements hook_session_template_insert().
 */
function la_pills_analytics_session_template_insert(SessionTemplate $session_template) {
  $manager = \Drupal::service('la_pills_analytics.manager');
  $request = \Drupal::request();

  $manager->storeAction('create', $request, [
    'template' => [
      'uuid' => $session_template->uuid,
      'title' => $session_template->getTitle(),
    ],
  ]);
}

/**
 * Implements hook_session_template_delete().
 */
function la_pills_analytics_session_template_delete(SessionTemplate $session_template) {
  $manager = \Drupal::service('la_pills_analytics.manager');
  $request = \Drupal::request();

  $manager->storeAction('delete', $request, [
    'template' => [
      'uuid' => $session_template->uuid,
      'title' => $session_template->getTitle(),
    ],
  ]);
}

/**
 * Implements hook_session_entity_enable_quick_feedback().
 */
function la_pills_analytics_session_entity_enable_quick_feedback(SessionEntityInterface $session, LaPillsQuestionnaireEntityInterface $questionnaire) {
  \Drupal::service('la_pills_analytics.manager')
    ->storeEntityAction($session, 'enable_quick_feedback', \Drupal::request(), [
      'questionnaire' => [
        'type' => 'quick_feedback',
        'id' => $questionnaire->id(),
        'uuid' => $questionnaire->uuid(),
        'title' => $questionnaire->label(),
      ],
    ]);
}

/**
 * Implements hook_session_entity_enable_activity_log().
 */
function la_pills_analytics_session_entity_enable_activity_log(SessionEntityInterface $session, array $activities) {
  $manager = \Drupal::service('la_pills_analytics.manager');
  $manager->storeEntityAction($session, 'enable_activity_log', \Drupal::request(), [
    'activities' => array_map(function(EntityInterface $entity) use ($manager) {
      return $manager->getEntityData($entity);
    }, $activities),
  ]);
}

/**
 * Implements hook_user_package_preview().
 */
function la_pills_analytics_user_package_preview(LaPillsUserPackageEntityInterface $entity) {
  \Drupal::service('la_pills_analytics.manager')
    ->storeEntityAction($entity, 'preview', \Drupal::request());
}

// TODO This indicates User Package being selected and not a fact that package
// contnts are being applied to the user. Activities and questions depend on
// permissions being present and being present within the package.
/**
 * Implements hook_user_package_apply().
 */
function la_pills_analytics_user_package_apply(LaPillsUserPackageEntityInterface $entity, UserInterface $user) {
  \Drupal::service('la_pills_analytics.manager')
    ->storeEntityAction($entity, 'apply_user_package', \Drupal::request(), [
      'user' => [
        'id' => $user->id(),
        'uuid' => $user->uuid(),
        'name' => $user->getAccountName(),
      ],
    ]);
}
