<?php

/**
 * @file
 * Contains la_pills_analytics.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_help().
 */
function la_pills_analytics_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the la_pills_analytics module.
    case 'help.page.la_pills_analytics':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('LAPills statistics and analytics.') . '</p>';
      return $output;

    default:
  }
}

function la_pills_analytics_session_entity_create(EntityInterface $entity) {
  // XXX Seems to be added twice
  $manager = \Drupal::service('la_pills_analytics.manager');
  $request = \Drupal::request();

  $manager->storeAction('create', $request);
}

function la_pills_analytics_session_entity_update(EntityInterface $entity) {
  $manager = \Drupal::service('la_pills_analytics.manager');
  $request = \Drupal::request();

  $manager->storeAction('update', $request);
}

function la_pills_analytics_session_entity_delete(EntityInterface $entity) {
  $manager = \Drupal::service('la_pills_analytics.manager');
  $request = \Drupal::request();

  $manager->storeAction('delete', $request);
}

function la_pills_analytics_la_pills_timer_entity_create(EntityInterface $entity) {
  $manager = \Drupal::service('la_pills_analytics.manager');
  $request = \Drupal::request();

  $manager->storeAction('create', $request);
}

function la_pills_analytics_la_pills_timer_entity_update(EntityInterface $entity) {
  $manager = \Drupal::service('la_pills_analytics.manager');
  $request = \Drupal::request();

  $manager->storeAction('update', $request);
}

function la_pills_analytics_la_pills_timer_entity_delete(EntityInterface $entity) {
  $manager = \Drupal::service('la_pills_analytics.manager');
  $request = \Drupal::request();

  $manager->storeAction('delete', $request);
}

function la_pills_analytics_la_pills_question_entity_create(EntityInterface $entity) {
  // XXX Seems to be added twice
  $manager = \Drupal::service('la_pills_analytics.manager');
  $request = \Drupal::request();

  $manager->storeAction('create', $request);
}

function la_pills_analytics_la_pills_question_entity_update(EntityInterface $entity) {
  $manager = \Drupal::service('la_pills_analytics.manager');
  $request = \Drupal::request();

  $manager->storeAction('update', $request);
}

function la_pills_analytics_la_pills_question_entity_delete(EntityInterface $entity) {
  $manager = \Drupal::service('la_pills_analytics.manager');
  $request = \Drupal::request();

  $manager->storeAction('delete', $request);
}

function la_pills_analytics_la_pills_user_package_create(EntityInterface $entity) {
  // XXX Seems to be added twice
  $manager = \Drupal::service('la_pills_analytics.manager');
  $request = \Drupal::request();

  $manager->storeAction('create', $request);
}

function la_pills_analytics_la_pills_user_package_update(EntityInterface $entity) {
  $manager = \Drupal::service('la_pills_analytics.manager');
  $request = \Drupal::request();

  $manager->storeAction('update', $request);
}

function la_pills_analytics_la_pills_user_package_delete(EntityInterface $entity) {
  $manager = \Drupal::service('la_pills_analytics.manager');
  $request = \Drupal::request();

  $manager->storeAction('delete', $request);
}

function la_pills_analytics_questionnaire_answered(array $questionnaire, EntityInterface $entity) {
  $manager = \Drupal::service('la_pills_analytics.manager');
  $request = \Drupal::request();

  $manager->storeAction('answered', $request);
}

function la_pills_analytics_quick_feedback_answered(EntityInterface $questionnaire, EntityInterface $entity) {
  $manager = \Drupal::service('la_pills_analytics.manager');
  $request = \Drupal::request();

  $manager->storeAction('answered', $request);
}
