<?php

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;
use Drupal\Core\Link;

/**
 * Implements hook_theme()
 */
function la_pills_theme($existing) {
  return [
    'session_entity' => [
      'render element' => 'elements',
      'file' => 'session_entity.page.inc',
    ],
    'session_template' => [
      'variables' => [
        'template' => NULL,
        'replacements' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_user_login().
 */
function la_pills_user_login($account) {
  $request = \Drupal::request();

  if ($request->cookies->has('Drupal_la_pills_session_entity_redirect_to')) {
    $id = (int) $request->cookies->get('Drupal_la_pills_session_entity_redirect_to');
    $response = new RedirectResponse(Url::fromRoute('entity.session_entity.canonical', ['session_entity' => $id,])->toString());
    $response->headers->clearCookie('Drupal.la_pills.session_entity_redirect_to');
    $response->send();
    return;
  }
}

/**
 * Callback that returns options for all available session template options.
 * @param Drupal\Core\Field\BaseFieldDefinition     $definition
 *   Field sefinition
 * @param Drupal\Core\Entity\ContentEntityInterface $entity
 *   Entity
 * @param bool                                      $cacheable
 *   Cache definition
 * @return array
 *   An array of options
 */
function _la_pills_session_template_allowed_values(BaseFieldDefinition $definition, ContentEntityInterface $entity = NULL, $cacheable) {
  $manager = \Drupal::service('la_pills.sesion_template_manager');

  $options = [];
  $templates = $manager->getTemplates();

  foreach ($templates as $template) {
    $options[$template->uuid] = '&nbsp;';
    $options[$template->uuid] .= Link::createFromRoute($template->getData()['context']['title'], 'session_template.preview', [
      'session_template' => $template->uuid,
    ], [
      'absolute' => TRUE,
      'attributes' => [
        'target' => '_blank',
      ]
    ])->toString();
    $options[$template->uuid] .= '<p>' . $template->getData()['context']['description']. '</p>';
  }

  return $options;
}
