<?php

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;
use Drupal\Core\Link;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldDefinitionInterface;

/**
 * Implements hook_theme()
 */
function la_pills_theme($existing) {
  return [
    'session_entity' => [
      'render element' => 'elements',
      'file' => 'session_entity.page.inc',
    ],
    'session_template' => [
      'variables' => [
        'template' => NULL,
        'replacements' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_page_attachments()
 */
function la_pills_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'la_pills/main';
}

/**
 * Implements hook_user_login().
 */
function la_pills_user_login($account) {
  $request = \Drupal::request();

  if ($request->cookies->has('Drupal_la_pills_session_entity_redirect_to')) {
    $id = (int) $request->cookies->get('Drupal_la_pills_session_entity_redirect_to');
    $response = new RedirectResponse(Url::fromRoute('entity.session_entity.canonical', ['session_entity' => $id,])->toString());
    $response->headers->clearCookie('Drupal.la_pills.session_entity_redirect_to');
    $response->send();
    return;
  }
}

/**
 * Callback that returns options for all available session template options.
 * @param Drupal\Core\Field\BaseFieldDefinition     $definition
 *   Field sefinition
 * @param Drupal\Core\Entity\ContentEntityInterface $entity
 *   Entity
 * @param bool                                      $cacheable
 *   Cache definition
 * @return array
 *   An array of options
 */
function _la_pills_session_template_allowed_values(BaseFieldDefinition $definition, ContentEntityInterface $entity = NULL, $cacheable) {
  $manager = \Drupal::service('la_pills.session_template_manager');

  $options = [];
  $templates = $manager->getTemplates();

  foreach ($templates as $template) {
    $options[$template->uuid] = '&nbsp;';
    $options[$template->uuid] .= Link::createFromRoute($template->getData()['context']['title'], 'session_template.preview', [
      'session_template' => $template->uuid,
    ], [
      'absolute' => TRUE,
      'attributes' => [
        'target' => '_blank',
      ]
    ])->toString();
    $options[$template->uuid] .= '<p>' . $template->getData()['context']['description']. '</p>';
  }

  return $options;
}

/**
 * Callback that generates a unique numeric code and checks that one does not
 * yet exist within the same column of the entity table.
 *
 * @param  Drupal\Core\Entity\FieldableEntityInterface $entity
 *   Entity being created/updated
 * @param  Drupal\Core\Field\FieldDefinitionInterface $definition
 *   Field definition
 *
 * @return string
 *   Unique code that consists of numbers
 */
function _la_pills_unique_session_numeric_code(FieldableEntityInterface $entity, FieldDefinitionInterface $definition) {
  $manager = \Drupal::service('la_pills.session_entity_code_manager');
  $base_table = $entity->getEntityType()->getBaseTable();
  $field_name = $definition->getName();

  return $manager->generateUniqueCode($base_table, $field_name, 6);
}
