<?php

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_theme()
 */
function la_pills_theme($existing) {
  return [
    'session_entity' => [
      'render element' => 'elements',
      'file' => 'session_entity.page.inc',
    ],
    'session_entity_dashboard' => [
      'variables' => [],
      'template' => 'session-entity--dashboard',
    ],
  ];
}

/**
 * Callback that returns options for all available session template options.
 * @param Drupal\Core\Field\BaseFieldDefinition     $definition
 *   Field sefinition
 * @param Drupal\Core\Entity\ContentEntityInterface $entity
 *   Entity
 * @param bool                                      $cacheable
 *   Cache definition
 * @return array
 *   An array of options
 */
function _la_pills_session_template_allowed_values(BaseFieldDefinition $definition, ContentEntityInterface $entity = NULL, $cacheable) {
  $manager = \Drupal::service('la_pills.sesion_template_manager');

  $options = [];
  $templates = $manager->getTemplates();

  foreach ($templates as $template) {
    $options[$template->uuid] = $template->getData()['context']['title'] . '<p>' . $template->getData()['context']['description']. '</p>';
  }

  return $options;
}
