<?php

use Drupal\Core\Link;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\la_pills\Entity\SessionEntityInterface;

/**
 * Implements hook_theme().
 */
function la_pills_timer_theme() : array {
  return [
    'la_pills_timers' => [
      'variables' => [
        'student' => NULL,
        'teacher' => NULL,
        'other' => NULL,
        'new_timer' => NULL,
      ],
    ],
    'la_pills_timer_elements' => [
      'variables' => ['elements' => NULL]
    ],
    'la_pills_session_timers' => [
      'variables' => [
        'student' => NULL,
        'teacher' => NULL,
        'other' => NULL,
        'stop_timers' => NULL,
        'download_data' => NULL,
      ],
    ],
    'la_pills_session_timer_elements' => [
      'variables' => ['elements' => NULL]
    ],
  ];
}

/**
 * Implements template_preprocess_la_pills_timer_elements().
 */
function template_preprocess_la_pills_timer_elements(&$variables) : void {
  if (!empty($variables['elements'])) {
    foreach ($variables['elements'] as $key => $element) {
      if (isset($element['#la_pills_timer_entity'])) {
        $entity = $element['#la_pills_timer_entity'];
        $timer_id = $entity->id();

        $options = [
          'attributes' => [
            'class' => ['use-ajax',],
            'data-dialog-type' => 'modal',
          ],
        ];

        $remove_link_options = $options;
        $remove_link_options['attributes']['class'][] = 'text-danger';

        $parameters = [
          'timer' => $timer_id,
        ];

        $remove_link = Link::createFromRoute(t('Remove'),'la_pills_timer.la_pills_timer_controller_removeTimer', $parameters, $remove_link_options);
        $edit_link = Link::createFromRoute(t('Edit'),'la_pills_timer.la_pills_timer_controller_editTimer', $parameters, $options);
        $change_status = [
          '#type' => 'checkbox',
          '#attributes' => [
            'title' => t('Mark timer as active'),
            'data-toggle' => 'tooltip',
            'checked' => $entity->getStatus() ? TRUE : FALSE,
            'disabled' => 'disabled',
          ],
        ];

        $timer_color = [
          '#type' => 'html_tag',
          '#tag' => 'span',
          '#value' => '',
          '#attributes' => [
            'class' => [
              'timer-color',
            ],
            'style' => [
              'background-color: ' . $entity->get('color')->value,
            ],
          ],
        ];

        $variables['elements'][$key]['change_status'] = $change_status;
        $variables['elements'][$key]['edit_link'] = $edit_link;
        $variables['elements'][$key]['remove_link'] = $remove_link;
        $variables['elements'][$key]['timer_color'] = $timer_color;
      }
    }
  }
}

/**
 * Implements template_preprocess_la_pills_timer_elements().
 */
function template_preprocess_la_pills_session_timer_elements(&$variables) : void {
  if (!empty($variables['elements'])) {
    foreach ($variables['elements'] as $key => $element) {
      if (isset($element['#la_pills_session_timer_entity'])) {
        $entity = $element['#la_pills_session_timer_entity'];
        $timer_id = $entity->id();
        $duration = $entity->getCurrentDuration();

        $parameters = [
          'session_entity' => $entity->getSessionId(),
          'timer_id' => $timer_id
        ];

        $session_option = [
          'attributes' => [
            'class' =>[
              'use-ajax',
              'timer-session-button',
              'lapills-timer-time-' . $timer_id
            ],
            'data-duration' => $duration,
          ]
        ];

        if ($entity->hasField('color') && $entity->get('color')->value) {
          $session_option['attributes']['style'] = 'background-color: ' . $entity->get('color')->value . ';';
        }

        if ($entity->getStatus()) {
          $session_option['attributes']['class'][] = 'la-pills-active-timer';
        }

        // XXX Timer is unable to show days, it stps with hours
        // This representation should be similar
        if (gmdate('d', $duration) == '01') {
          $time = gmdate('H:i:s', $duration);
        } else {
          // This one is a bit strange
          $time = intval(gmdate('d', $duration)) - 1 . gmdate(':H:i:s', $duration);
        }

        $session_link = Link::createFromRoute(
          $time,
          'la_pills_timer.la_pills_timer_controller_sessionTimer',
          $parameters,
          $session_option);

        $variables['elements'][$key]['session_link'] = $session_link;
      }
    }
  }
}

/**
 * Callback for Session Entity create/edit form being submitted. Would only be
 * called if it is possible to attach timers.
 *
 * @param array             $form
 *   From structure
 * @param FormStateInterface $form_state
 *   Form state object
 */
function _la_pills_timer_session_entity_form_submitted(array &$form, FormStateInterface $form_state) : void {
  $values = $form_state->getValues();

  if (isset($values['use_timers']) && $values['use_timers']) {
    $timer_manager = \Drupal::service('la_pills_timer.manager');
    $entity = $form_state->getFormObject()->getEntity();

    $entity_timers_count = $timer_manager->getSessionEntityTimersCount($entity);

    if ($entity_timers_count > 0) {
      return;
    }

    $timers = $timer_manager->getCurrentUserActiveTimers();

    if ($timers) {
      foreach($timers as $timer) {
        $session_timer = \Drupal::entityTypeManager()
          ->getStorage('la_pills_session_timer_entity')
          ->create([
            'session_id' => $entity->id(),
            'name' => $timer->getName(),
            'group' => $timer->getTimerGroup(),
            'color' => $timer->get('color')->value,
          ]);
        $session_timer->save();
      }
    }
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function la_pills_timer_form_session_entity_form_alter(&$form, FormStateInterface $form_state, $form_id) : void {
  if (in_array($form_id, ['session_entity_add_form', 'session_entity_edit_form',]) && \Drupal::currentUser()->hasPermission('add la pills timer entities')) {
    $timer_manager = \Drupal::service('la_pills_timer.manager');
    $entity = $form_state->getFormObject()->getEntity();

    $form['la_pills_timer'] = [
      '#type' => 'container',
      '#weight' => 50,
      '#attributes' => [
        'class' => ['well',],
      ],
    ];

    if ($entity->id()) {
      $entity_timers_count = $timer_manager->getSessionEntityTimersCount($entity);

      if ($entity_timers_count > 0) {
        $form['la_pills_timer']['explanation'] = [
          '#type' => 'container',
          '#attributes' => [
            'class' => ['alert', 'alert-info',],
          ],
        ];
        $form['la_pills_timer']['explanation']['text'] = [
          '#markup' => t('Data gathering session has @count timers attached to it.', [
            '@count' => $entity_timers_count,
          ]),
        ];

        return;
      }
    }

    $timers_count = $timer_manager->getCurrentUserTimerCount();
    $active_timers_count = $timer_manager->getCurrentUserActiveTimerCount();

    $form['la_pills_timer']['explanation'] = [
      '#type' => 'container',
      '#attributes' => [
        'class' => ['alert', 'alert-info',],
      ],
    ];
    $form['la_pills_timer']['explanation']['text'] = [
      '#markup' => t('You have @active active timers out of @total total timers. Please access <a href=":url" target="_blank">activity log configuration page</a> to make changes.', [
        '@active' => $active_timers_count,
        '@total' => $timers_count,
        ':url' => Url::fromRoute('la_pills_timer.la_pills_timer_controller_timers')->toString(),
      ]),
    ];
    $form['la_pills_timer']['use_timers'] = [
      '#type' => 'checkbox',
      '#title' => t('Enable activity logging'),
      '#default_value' => $entity->id() ? 0 : 1,
      '#disabled' => $active_timers_count > 0 ? FALSE : TRUE,
      '#attributes' => [
        'title' => t('Make a copy of your currrently active timers and use those for this session. Please note that this can no longer be changed.'),
        'data-toggle' => 'tooltip',
      ],
    ];

    $form['actions']['submit']['#submit'][] = '_la_pills_timer_session_entity_form_submitted';
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete().
 */
function la_pills_timer_session_entity_predelete(SessionEntityInterface $entity) : void {
  // TODO Consider maing the process a lo more resource friendly by either
  // running the delete according to the drupal API logic within a cron job or
  // using direct database queries to delete all the data, bypassing the API
  $timer_manager = \Drupal::service('la_pills_timer.manager');
  $timers = $timer_manager->getSessionEntityTimers($entity);

  if ($timers) {
    foreach($timers as $timer) {
      // TODO Deal with possible permission issues, if there are any
      $timer->delete();
    }
  }
}

/**
 * Implements hook_session_entity_session_close().
 */
function la_pills_timer_session_entity_session_close(SessionEntityInterface $entity) : void {
  $timer_manager = \Drupal::service('la_pills_timer.manager');
  $timer_manager->stopAllActiveTimers($entity);
}

/**
 * Implements hook_la_pills_session_entity_view_alter().
 */
function la_pills_timer_la_pills_session_entity_view_alter(array &$content, SessionEntityInterface $session_entity) : void {
  // TODO See if this clashes with caching
  $timer_manager = \Drupal::service('la_pills_timer.manager');

  if ($timer_manager->canAccessSessionEntityTimersPage($session_entity)) {
    $content['alerts']['timers_attached'] = [
      '#type' => 'container',
      '#attributes' => [
        'class' => ['alert', 'alert-info',],
      ],
      '#weight' => -5,
    ];
    $content['alerts']['timers_attached']['text'] = [
      '#markup' => t('You have activated activity logging. Please log your activities <a href=":url">here</a>.', [
        ':url' => Url::fromRoute('la_pills_timer.la_pills_timer_controller_sessionEntityTimers', [
          'session_entity' => $session_entity->id(),
        ])->toString(),
      ]),
    ];
  }
}
